/* automatically generated by rust-bindgen 0.66.1 */

extern "C" {
    pub fn util_sum(count: ::core::ffi::c_int, ...) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn util_mult(
        val1: ::core::ffi::c_int,
        val2: ::core::ffi::c_int,
        p_out: *mut ::core::ffi::c_int,
    ) -> bool;
}
extern "C" {
    pub fn util_random(min_val: i32, max_val: i32, p_out: *mut i32) -> bool;
}
